const DenseGraph = require('./01-DenseGraph')
const SparseGraph = require('./02-SparseGraph')
const { readGraph } = require('./utils')

;(async function () {
  const denseGraph = new DenseGraph(14, false)
  await readGraph(denseGraph, 'testG1.txt')
  denseGraph.show()
  console.log('连通分量: ' + denseGraph.getComponentCount())
  denseGraph.dfsPath(0, 4)
  denseGraph.bfsPath(0, 4)
  const sparseGraph = new SparseGraph(9, false)
  await readGraph(sparseGraph, 'testG2.txt')
  sparseGraph.show()
  console.log('连通分量: ' + sparseGraph.getComponentCount())
  sparseGraph.dfsPath(0, 5)
  sparseGraph.bfsPath(0, 5)
})()
